# Generated by Django 4.1.3 on 2023-03-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_stockbasics'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbasics',
            name='area',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='stockbasics',
            name='industry',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='stockbasics',
            name='list_date',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
