# Generated by Django 4.1.3 on 2023-03-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_stockbasics_area_stockbasics_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=1000)),
                ('platform', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 't_stock_news',
            },
        ),
    ]
