# Generated by Django 4.1.3 on 2023-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_stocknews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknews',
            name='type',
            field=models.CharField(max_length=500),
        ),
    ]
