# Generated by Django 4.1.3 on 2023-03-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_alter_stocknews_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknews',
            name='platform',
            field=models.CharField(default='新浪', max_length=1000),
        ),
        migrations.AlterField(
            model_name='stocknews',
            name='type',
            field=models.CharField(default=1, max_length=500, verbose_name='1 A股'),
        ),
    ]
